language: node_js
node_js:
  - '10'
cache: yarn

os:
   - windows
#  - osx
#  - linux
  

install:
  - yarn install
  - yarn run build
  - yarn run dist

deploy:
  draft: true
  edge: true
  file_glob: true
  overwrite: true
  provider: releases
  on:
    tags: true
    all_branches: true
